iotile/coretools

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/adapterstream.py, iotilecore/iotile/core/hw/transport/cmdstream.py, iotilecore/version.py, transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py, transport_plugins/bled112/test/test_bled112_adapterstream.py, transport_plugins/bled112/test/util/dummy_serial.py, transport_plugins/bled112/version.py
Errors on connections we not properly checked leading to hangs with exceptions being thrown in background threads.
Now:
- bled112 should be robust against malformed connection strings, just failing but not hanging
- connections opened use HardwareManager(port='bled112:<auto>,STRING') that fail should not longer hang
- adapterstream now checks the return status of calls and converts failures to exceptions
=> Improve error checking on connections in bled112 and adapterstream

iotilebuild/RELEASE.md, iotilebuild/iotile/build/plugin.py, iotilebuild/iotile/build/release/null_provider.py, iotilebuild/iotile/build/release/provider.py, iotilebuild/iotile/build/release/release.py, iotilebuild/setup.py, iotilebuild/test/test_release/dev_mode_comp/build/output/module_settings.json, iotilebuild/test/test_release/dev_mode_comp/module_settings.json, iotilebuild/test/test_release/fail_first_release_comp/module_settings.json, iotilebuild/test/test_release/fail_first_stage_comp/module_settings.json, iotilebuild/test/test_release/fail_second_release_comp/module_settings.json, iotilebuild/test/test_release/fail_second_stage_comp/module_settings.json, iotilebuild/test/test_release/nosteps_comp/module_settings.json, iotilebuild/test/test_release/successful_release_comp/module_settings.json, iotilebuild/test/test_release/test_release.py, iotilebuild/test/test_release/unbuilt_dev_mode_comp/module_settings.json, iotilebuild/test/test_release/unknown_provider_comp/module_settings.json, iotilebuild/version.py, iotilecore/RELEASE.md, iotilecore/iotile/core/dev/iotileobj.py, iotilecore/test/test_dev/releasesteps_good_component/module_settings.json, iotilecore/test/test_dev/releasesteps_invalid_component/module_settings.json, iotilecore/test/test_dev/test_iotile.py, iotilecore/version.py
Added the concept of ReleaseProviders to iotile-build and a new plugin ```iotile release```.
```iotile release``` will look at a list of release steps stored in module_settings.json, match them to ReleaseProvider subclasses and then execute them one by one.  This provides the infrastructure needed to allow releasing iotile components like firmware images.
Closes #68.
=> Add support for iotile release command

iotilebuild/RELEASE.md, iotilebuild/setup.py, iotilebuild/version.py, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/reports/__init__.py, iotilecore/iotile/core/hw/reports/parser.py, iotilecore/iotile/core/hw/reports/report.py, iotilecore/iotile/core/hw/reports/signed_list_format.py, iotilecore/setup.py, iotilecore/test/test_reports/test_individual_report.py, iotilecore/test/test_reports/test_report_parser.py, iotilecore/test/test_reports/test_signed_list_report.py, iotilecore/version.py, iotiletest/RELEASE.md, iotiletest/iotile/mock/devices/report_test_device.py, iotiletest/setup.py, iotiletest/version.py
This just includes basic support.  Hooks for actually verifying signatures and generating them for internally generated reports are still forthcoming.
=> Add signed lists of readings as a new supported report type

iotile_ext_cloud/iotile/cloud/cloud.py, iotilebuild/iotile/build/dev/depmanager.py, iotilebuild/iotile/build/dev/resolverchain.py, iotilebuild/iotile/build/dev/resolvers/registry_resolver.py, iotilebuild/test/test_depresolvers/test_resolverchain.py, iotilebuild/test/test_iotilebuild/component_nodependskey/build/output/module_settings.json, iotilecore/iotile/core/dev/config.py, iotilecore/iotile/core/dev/iotileobj.py, iotilecore/iotile/core/exceptions.py, iotilecore/iotile/core/hw/auth/auth_chain.py, iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/hw/reports/signed_list_format.py, iotilecore/iotile/core/hw/transport/websocketstream.py, iotilecore/iotile/core/utilities/stoppable_thread.py, iotilecore/iotile/core/utilities/validating_wsclient.py, iotilecore/test/test_reports/test_signed_list_report.py, iotilecore/test/test_utilities/test_stoppable_thread.py, iotiletest/iotile/mock/mock_resolver.py, transport_plugins/awsiot/iotile_transport_awsiot/gateway_agent.py, transport_plugins/awsiot/iotile_transport_awsiot/mqtt_client.py, transport_plugins/bled112/iotile_transport_bled112/async_packet.py, transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py, transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py
Legacy cleanup
There were internal exceptions named EnvironmentError and TimeoutError that shadow builtin exceptions.  This replaces them with ExternalError and TimeoutExpiredError.
Closes #188
=> Remove improperly named exceptions

transport_plugins/bled112/iotile_transport_bled112/bled112.py
Dictionary access inside of `_get_connection` was made safer, along with a slight refactor of calling code.
=> avoid connection key error

transport_plugins/awsiot/iotile_transport_awsiot/gateway_agent.py
At the point when a conditional check is done to see whether the connection succeeded, `uuid` is guaranteed to not be inside of `self._connections` (this method would have already returned before this code is reached if otherwise), and `self._connections[uuid]` does not get initialized. This dict entry for `uuid` is now initialized with an empty dict to avoid a key error in the subsequent code.
=> prevent key error on failed gateway connection

iotilecore/iotile/core/utilities/paths.py, iotilecore/test/test_utilities/test_settings_dir.py
Mac now uses the same path as Linux: `~/.config/`
=> Change settings_directory directory for Mac

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/version.py
Closes #231
If a previous process died in a specifically dirty fashion, the dongle
could not allow future processes to initialize it because the start
scan command would fail since scanning was already in progress.
=> Bugfix bled112 initialization error

iotilebuild/iotile/build/config/site_scons/autobuild.py
The windows powershell issue is being caused by misinterpreted ascii color codes being emitted by `sphinx-build` as it builds our firmware documentation.  Until `sphinx` is fixed, the workaround is to just disable color output on windows.  
I verified that this fixes the issue on my windows builds.
Closes #239
=> Fix sphinx-build colorization issue on powershell

iotile_ext_cloud/iotile/__init__.py, iotile_ext_cloud/iotile/cloud/__init__.py, iotile_ext_cloud/iotile/cloud/utilities.py, iotile_ext_cloud/test/test_utils.py
Adds a device_id_to_slug function that should work for the entire lifespan of the slug format as currently defined ( `d--xxxx-xxxx-xxxx-xxxx` ). Unit tested.
Also adds imports exports in `__init__`
=> Feat utils

iotile_ext_cloud/iotile/cloud/cloud.py, iotile_ext_cloud/test/large_mock_answer.json, iotile_ext_cloud/test/test_login.py
`get_whitelist` should raise an ExternalError when the whitelist is empty, but it does not as the gateway itself is removed after this trial.
This commit fixes that, and adds a new test to make sure this does not happen again
=> Feat fleets bugfix

iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/graph.py, iotilesensorgraph/iotile/sg/node.py, iotilesensorgraph/iotile/sg/parser/language.py, iotilesensorgraph/iotile/sg/parser/parser_v1.py, iotilesensorgraph/iotile/sg/parser/statements/on_block.py, iotilesensorgraph/iotile/sg/stream.py, iotilesensorgraph/test/sensor_graphs/basic_on_dual.sgf, iotilesensorgraph/test/test_compiler.py, iotilesensorgraph/test/test_parsing.py, iotilesensorgraph/version.py
This PR adds support for on block syntax like:
```
on value(input 5) and value(constant 1) == 2
{
}
```
Closes #293
=> Add support for two conditions in an on block

iotilecore/iotile/core/dev/annotated_registry.py, iotilecore/iotile/core/scripts/iotile_script.py, iotilecore/test/test_shell/test_iotile_cmd.py, iotilesensorgraph/iotile/sg/node.py, iotilesensorgraph/iotile/sg/node_descriptor.py, iotilesensorgraph/iotile/sg/processors.py, iotilesensorgraph/iotile/sg/stream.py, iotilesensorgraph/test/test_datastream.py, iotilesensorgraph/test/test_nodeparsing.py
Major changes:
- iotile-sensorgraph can now parse the binary RPC payloads that generate embedded sensorgraph nodes.
- fix the incorrect pluralization of buffered streams
- add some basic unit test coverage of the `iotile` shell tool.
Closes #311
Closes #306
=> Add support for parsing binary node descriptors in iotile-sensorgraph

iotilegateway/test/test_supervisor_commands.py
The test case shows how to setup everything required to invoke an RPC on an RPCDisptacher subclass that is connected to an IOTileSupervisor.  The invocation is made using `HardwareManager` by creating an appropriate config file that sets up a virtual device pointing at the desired service.
=> Add test case covering the use of service_delegate tile.

iotile_ext_cloud/iotile/cloud/utilities.py, iotile_ext_cloud/setup.py
Which requires IOTileDeviceSlug users to pass a `allow_64bits=False` if
they want a check for 48bit limit. If this change is not done, test
will fail next time somebody pip installs v0.8.11. No need to release
this change
=> Upgrade to using iotile_cloud v0.8.11

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/pythondist.py, iotilebuild/version.py, iotilecore/RELEASE.md, iotilecore/iotile/core/dev/iotileobj.py
@x24ling Take a look at this then I'll merge and release.
You can now specify a custom `iotile-ship` build step in `module_settings.json` products using:
```typescript
"products":
{
"python/build_step_whatever.py": "build_step"
}
```
The value of the product key should be `build_step`.
=> Add support for custom build steps as part of component builds.

iotile_ext_cloud/iotile/cloud/cloud.py, iotilecore/iotile/core/scripts/iotile_script.py, iotilecore/test/test_shell/test_iotile_cmd.py, iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/output_formats/ascii.py, iotilesensorgraph/iotile/sg/output_formats/config.py, iotilesensorgraph/iotile/sg/output_formats/snippet.py, iotilesensorgraph/test/test_integration/reference_output/usertick_optimized_ascii.txt, iotilesensorgraph/test/test_integration/reference_output/usertick_optimized_config.txt, iotilesensorgraph/test/test_integration/reference_output/usertick_optimized_snippet.txt, iotilesensorgraph/test/test_integration/test_output_formats.py, iotilesensorgraph/version.py
This fixes a regression in `0.6.0` introduced by a change to `DataStreamer` to fix some technical debt that prevented generation of binary scripts containing a compiled sensorgraph.  
It also patches some python 3 compatibility issues in `iotile-core` and adds an option to help with unit testing of the `iotile` tool.
Closes #398.
=> Fix regression in snippet output format and add test coverage

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/utilities.py, iotilebuild/test/test_iotilebuild/arm_component/module_settings.json, iotilebuild/version.py
Fixes bug #423 where build does not work on Macs.
=> Bug macbuild #423

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/cfileparser.py, iotilebuild/iotile/build/config/site_scons/unit_test_qemu.py, iotilebuild/test/test_iotilebuild/comp_with_tests/firmware/test/test_utilities.c, iotilebuild/version.py
- Properly copy over headers and referenced C modules
- Improve unit test to actually check and make sure the copying process is done correctly.
=> Fix unit test generation for qemu.

.travis.yml, iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/templates/qemu_semihost_unit/semihost.c, iotilebuild/iotile/build/config/templates/qemu_semihost_unit/semihost.h, iotilebuild/version.py, scripts/install_arm_gcc.sh
Semihost.c `svc()` did not properly mark its arguments as volatile, causing recent gcc versions to optimize them away resulting in undefined behavior.  The error was masked before `qemu` was not run on continuous integration to see this issue on linux.
=> Add QEMU to Travis, fix semihost.c on recent gcc

iotilebuild/RELEASE.md, iotilebuild/iotile/build/dev/depmanager.py, iotilebuild/version.py
This is a necessary extra feature before we can do recursive builds in a CI setting.
=> Add ability to find local dependencies

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py, transport_plugins/bled112/version.py
There were `str` vs `bytes` issues on python 3 that prevented the bled112 virtual interface from functioning.
Closes #470
=> Fix advertising data on python 3 in virtual devices.

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py, transport_plugins/bled112/version.py
Hopefully this is the last python 3 patch needed to make virtual devices on bled112 work on python 3.
=> Fix additional str to bytes error on python 3

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/utilities/linebuffer_ui.py, scripts/test.py
Addresses #445 and cleans up some of the code in affected files WRT pylint. 
Testing done:
* Executed function against multiple virtual devices (connect/disconnect, enable_streaming, etc)
* Executed function against real devices and verified that report results were showing up and changing over time
* Ran tests locally in the iotilecore/tests folder (this prompted the do_test changes) against python3 
Other review notes:
* travis-ci tests passing with @ekkizogloy 's fix on master
=> Feat watch 445

transport_plugins/bled112/iotile_transport_bled112/async_packet.py, transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py
As described in #515, quit doesn't finish gracefully if the bled112 dongle gets disconnected during use. Added some error handling to catch that and return the appropriate response for this modality.
Tested in both py2 and py3 by doing the following:
1) Turn on bled112 dongle
2) run ```iotile hw --port=bled112```
3) after utility opens, run ```quit```
4) verify that the python process actually quit
Right now, the user doesn't get feedback that something like this happened, but the root behavior of the program checking that the bled112 connection is "cleared" is still in place.
=> Improve iotile utility quit behavior

.pylintrc, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/debug/debug_manager.py, iotilecore/iotile/core/hw/transport/adapter.py, iotilecore/iotile/core/hw/transport/emulatedadapter.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/emulation/emulated_device.py, iotilecore/setup.py, iotilecore/test/test_hw/test_emulatedadapter.py, iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/virtual/feature_mixins/__init__.py, iotilesensorgraph/iotile/sg/virtual/feature_mixins/remote_bridge.py, iotilesensorgraph/iotile/sg/virtual/reference_controller.py, iotilesensorgraph/iotile/sg/virtual/reference_device.py, iotilesensorgraph/test/test_reference.py, iotileship/test/test_recipe_manager/test_on_reference_device.py
This PR adds a new DeviceAdapter for use with emulated devices that provides access to their state {load,save,track} and scenario loading functionality from the `debug` interface in the `iotile` tool.
The adapter can be used by passing `--port=emulated:<args>` to `iotile hw` and has all of the same features as using the virtual device adapter except that it only works with emulated devices and it provides additional debug routines:
- save_snapshot, load_snapshot: Save and load the current internal state on a connected emulated device.
- open_scenario: Load a test scenario from a file into the currently connected device.
- track_changes: Start or stop tracking all internal state changes on your emulated device.
- save_changes: Save the log of all internal changes on your connected device …
=> Add EmulatedDeviceAdapter device adapter.

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/common_types.py, iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/constants/rpc_tilemanager.py, iotileemulate/iotile/emulate/reference/controller_features/config_database.py, iotileemulate/iotile/emulate/reference/controller_features/tile_manager.py, iotileemulate/iotile/emulate/transport/emulatedadapter.py, iotileemulate/iotile/emulate/virtual/emulated_device.py, iotileemulate/iotile/emulate/virtual/emulated_tile.py, iotileemulate/iotile/emulate/virtual/peripheral_tile.py, iotileemulate/test/test_reference.py, iotileemulate/tox.ini, tox.ini
Fixes a few bugs found during testing.  There is now test coverage on all RPCs in the config_database and tile_manager subsystems.
Additionally there is test covergae of config variable streaming to a peripheral tile and proper clearing of config variables on reset with streaming of new data from the controller.
@mattrunchey 
For ease of testing, this adds the ability to pass premade DeviceAdapter classes to HardwareManager.  This obviates in some cases the need to serialize device states and pass them as base64 encoded strings.
Closes #545
=> Add test coverage of config_database and tile_manager subsystems.

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/__init__.py, iotilecore/iotile/core/hw/virtual/common_types.py, iotilecore/iotile/core/utilities/__init__.py, iotilecore/iotile/core/utilities/workqueue_thread.py, iotilecore/test/test_utilities/test_workqueue.py, iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/constants/__init__.py, iotileemulate/iotile/emulate/constants/rpc_config_variables.py, iotileemulate/iotile/emulate/constants/rpcs.py, iotileemulate/iotile/emulate/reference/reference_device.py, iotileemulate/iotile/emulate/utilities/__init__.py, iotileemulate/iotile/emulate/utilities/format_rpc.py, iotileemulate/iotile/emulate/virtual/__init__.py, iotileemulate/iotile/emulate/virtual/emulated_device.py, iotileemulate/iotile/emulate/virtual/emulation_mixin.py, iotileemulate/iotile/emulate/virtual/peripheral_tile.py, iotileemulate/iotile/emulate/virtual/state_log.py
In preparation for supporting EmulatedTiles that have their own background work going on, we need a general way of synchronizing RPCs to execute one at a time without requiring the RPC function to be called from a single thread.
This PR refactors the RPC dispatch logic to use a single background work-queue as the sole RPC executor.  All calls to `rpc`, `deferred_rpc` and `call_rpc` are not synchronized through this queue.  
Additional Fixes:
- Adds a lot more docstring descriptions of what is going on and why
- adds a `format_rpc` function that can print a nice string describing an RPC call-and-response including looking up a good name for the RPC (so `SET_CONFIG_VARIABLE` rather than just `RPC 0x2001`).  This is used for state tracking so that the produced changelog is easier to …
=> Move RPC dispatch to a background workqueue

iotileemulate/iotile/emulate/reference/controller_features/sensor_log.py, iotileemulate/iotile/emulate/reference/reference_controller.py, iotileemulate/iotile/emulate/utilities/format_rpc.py, iotileemulate/test/test_reference.py, iotilesensorgraph/iotile/sg/sensor_log.py, iotilesensorgraph/test/test_sensorlog.py
This PR finishes RawSensorLog support for ReferenceController including the remaining support for state snapshoting.
Closes #560
=> Finish sensor_log subsystem in emulated controller

iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/constants/rpc_sensorgraph.py, iotileemulate/iotile/emulate/constants/rpc_sensorlog.py, iotileemulate/iotile/emulate/reference/controller_features/sensor_graph.py, iotileemulate/iotile/emulate/reference/controller_features/sensor_log.py, iotileemulate/test/test_reference_sensorgraph.py, iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/graph.py, iotilesensorgraph/iotile/sg/parser/language.py, iotilesensorgraph/iotile/sg/parser/statements/streamer_statement.py, iotilesensorgraph/iotile/sg/stream.py, iotilesensorgraph/iotile/sg/streamer.py, iotilesensorgraph/iotile/sg/streamer_descriptor.py, iotilesensorgraph/test/test_datastream.py, iotilesensorgraph/test/test_integration/test_complex_gate.py, iotilesensorgraph/test/test_streamer.py
This PR finishes adding basic support for streamers into the sensor-graph subsystem of `ReferenceController` in iotile-emulate.  It finishes support for `add_streamer` and `inspect_streamer` and adds some infrastructure to be able to generate reports from streamers.  Previously they were just plain data models designed to hold a description of the streamer but had no actual ability to use the streamer in any way.
**Remaining Work:**
- add basic stream manager subsystem that can take reports generated by sensor_graph and stream them out of the device.
- add support for state dump/restore
Tracked in #550
=> Add streamer support into sensorgraph subsystem in iotile-emulate

iotilecore/iotile/core/hw/reports/parser.py, iotilecore/iotile/core/hw/transport/websocketstream.py, iotilecore/test/test_reports/test_report_parser.py, iotilegateway/iotilegateway/main.py, iotilegateway/setup.py, iotilegateway/tox.ini, tox.ini, transport_plugins/awsiot/iotile_transport_awsiot/connection_manager.py, transport_plugins/awsiot/iotile_transport_awsiot/device_adapter.py, transport_plugins/awsiot/iotile_transport_awsiot/gateway_agent.py, transport_plugins/awsiot/iotile_transport_awsiot/mqtt_client.py, transport_plugins/awsiot/iotile_transport_awsiot/packet_queue.py, transport_plugins/awsiot/test/conftest.py, transport_plugins/awsiot/test/test_agent.py, transport_plugins/awsiot/tox.ini, transport_plugins/jlink/iotile_transport_jlink/jlink_background.py
Changes are separated in to two commits. The change for performance mostly just moves the repeated call to pkg_resources.load(). Since the report types aren't expected to change on runtime, we can just instantiate the types on import.
For awsiot changes, I fixed all of the py3 test failures and ran them against py2 again to ensure they are still working. There still may be changed behavior that I missed but it should be mostly localized to the awsiot transport plugin, which may be changing significantly anyways.
=> Improve iotile-gateway performance and prepare awsiot for py3

iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/hw/proxy/proxy.py, iotilecore/iotile/core/hw/virtual/__init__.py, iotilecore/iotile/core/hw/virtual/virtualtile.py, iotilecore/test/test_hw/test_virtualadapter.py
- RPC calls the new `unpack_rpc_payload` method now
- TileBusProxy dependency removed from VirtualTile. Only functional change for tests is that you need to use the new `load_development_proxy` when using `virtual:` with TileBusProxy objects. 
Tests executed on py2/py3 locally and passing.
=> Update RPC and TileBusProxy

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/exceptions.py, iotilecore/iotile/core/hw/proxy/proxy.py
Adds a workaround into `iotile-core` for https://github.com/iotile/lib_controller/issues/166.  This will allow us to reliably detect programmatically if an RPC failed because it was not implemented or for another reason.  
This is useful for `synchronize_rtc` in POD-1M v2 since older firmwares won't support that RPC and we want to distinguish that expected failure from an unexpected issue running the RPC itself.
=> Fix RPC CommandNotFound exception working around controller bug.

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/reports/utc_assigner.py, iotilecore/iotile/core/hw/transport/adapterstream.py, iotilecore/iotile/core/hw/virtual/common_types.py, iotilecore/iotile/core/utilities/workqueue_thread.py, iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/constants/rpc_clockmanager.py, iotileemulate/iotile/emulate/demo/demo_device.py, iotileemulate/iotile/emulate/reference/controller_features/clock_manager.py, iotileemulate/iotile/emulate/reference/controller_features/config_database.py, iotileemulate/iotile/emulate/reference/controller_features/sensor_graph.py, iotileemulate/iotile/emulate/reference/reference_controller.py, iotileemulate/iotile/emulate/reference/reference_device.py, iotileemulate/iotile/emulate/transport/emulatedadapter.py, iotileemulate/iotile/emulate/virtual/emulated_device.py, iotileemulate/iotile/emulate/virtual/emulated_tile.py, iotileemulate/test/test_clock.py, iotileemulate/test/test_emulatedadapter.py, iotileemulate/test/test_emulation.py
This PR merges some slight code cleanup of `iotile-emulate` that I had on a side branch and finishes initial support for asynchronous RPCs, which are RPCs whose handler function returns without giving a response.  From the caller's point of view, all RPCs (including these) are synchronous, so the caller remains blocked, however the actual response value is provided via a callback on `EmulatedDevice.finish_async_rpc` rather than the return value of the rpc handler itself.
This is an important feature for emulating many real-world tiles that extensively use asynchronous rpcs.
**Additional changes:**
- The reset handling logic of the emulator is slightly refactored to remove some race conditions
- The `EmulatedDeviceAdapter` is updated so that a device reset happens synchronously by the time …
=> Slightly cleanup iotile-emulate code and add support for asynchronous RPCs

doc/source/introduction.rst
I actually should probably go through more of the docs to make sure nothing else has changed significantly, either. There are still some places that we use this RTD info now (in some of our internal docs).
=> Update intro readme to install new dependency

iotilecore/RELEASE.md, iotilecore/iotile/core/dev/__init__.py, iotilecore/iotile/core/dev/iotileobj.py, iotilecore/iotile/core/dev/registry.py, iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/hw/proxy/external_proxy.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/virtualtile.py, iotilecore/iotile/core/scripts/virtualdev_script.py, iotilecore/test/test_dev/comp_w_products/module_settings.json, iotilecore/test/test_dev/releasemode_comp_w_prod/module_settings.json, iotilecore/test/test_dev/test_iotile.py, iotilecore/test/test_hw/test_appmatching.py, iotilecore/test/test_hw/test_virtualadapter.py, iotilegateway/test/test_supervisor_commands.py
This PR cleans up the process by which `iotile-core` finds and imports plugins.  Over the years there have been many copies of the same importing code committed.  This PR removes them all from `iotile-core` and replaces them with 4 routines on `ComponentRegistry`:
- `load_extensions`: will find and load all extensions of a given type that are either pip installed or locally installed using `ComponentRegistry.add_component()`.  
- `load_extension`: will directly load and validate a single `.py` file that contains an extension.  This allows for directly specifying paths to extensions when required.  It also provides the basis for the automatic `load_extensions` method above.
- `register_extension`: will programmatically add an extension temporarily that will then be returned when is matches …
=> Consolidate all extension importing code into a single place in iotile-core

iotilecore/RELEASE.md, iotilecore/iotile/core/dev/iotileobj.py, iotilecore/iotile/core/dev/registry.py, iotilecore/test/test_dev/oldstyle_built_component/build/output/module_settings.json, iotilecore/test/test_dev/oldstyle_built_component/module_settings.json, iotilecore/test/test_dev/test_iotile.py, iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/constants/rpc_controller.py, iotileemulate/iotile/emulate/constants/rpcs.py, iotileemulate/iotile/emulate/constants/streams.py, iotileemulate/iotile/emulate/reference/controller_features/config_database.py, iotileemulate/iotile/emulate/reference/controller_features/sensor_graph.py, iotileemulate/iotile/emulate/reference/reference_controller.py, iotileemulate/iotile/emulate/reference/reference_device.py, iotileemulate/iotile/emulate/virtual/__init__.py, iotileemulate/iotile/emulate/virtual/emulated_device.py, iotileemulate/iotile/emulate/virtual/emulated_tile.py, iotileemulate/test/test_reference_sensorgraph.py, iotileemulate/version.py, iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/output_formats/config.py, iotilesensorgraph/iotile/sg/parser/parser_v1.py, transport_plugins/websocket/RELEASE.md, transport_plugins/websocket/iotile_transport_websocket/virtual_websocket.py
This is the day's take of small fixes and incremental features.  
Most of the fixes address python 3 incompatibilities or chatty logs and there are few features added to `iotile-emulate`.
**Each commit in this PR is a feature or fix with a description and linked issue in the commit message**
The new `iotile-emulate` features are:
- Support for notifying the `sensor_graph` subsystem when a streaming interface is open on the device.  This is important because real-world `sgf` files reference this signal to know when to stream high-speed realtime updates.
- Support for directly loading an `sgf` file as a test scenario.  This allows us to produce POD emulators that come with their sensor_graphs already loaded.
- Support for reading the hardware string from `ReferenceController`.
- Support for …
=> A collection of small fixes and features for CoreTools

doc/source/introduction.rst, doc/source/tutorials/first-iotile-device.rst
Formatting and <TAB> printout updates, mostly.
We also need to rerun `sphinx-build`, because our HTML output isn't showing any of the blocks that use autodoc, for example:
```
.. py:module:: iotile.core.hw.hwmanager
.. autoclass:: HardwareManager
:members: iter_reports, enable_streaming
```
=> Update intro and first-iotile-device documentations

CONTRIBUTING.md, README.md, doc/source/contributing.rst
I tagged a lot of people to review this because it has a larger goal.
The goal with this is to set an easily discoverable place for someone to learn, at a high level, how we develop software at Arch. It pulls from a few internal resources that we've used in part in the past, and will simplify and unify our approach.
At this point, the contribution guide is, to an extent, open to suggestions and changes. I want everyone to be on the same page on what we're proposing before setting it as a standard. 
Please remember that this PR is presented in an open forum, so certain conversations may need to be taken offline if they are closely tied to Arch internals. Please message me if you have any doubts about where your comment should go!
=> Feat contribution guide

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/release.py, iotilebuild/iotile/build/dev/resolverchain.py, iotilebuild/version.py
This fixes issues related to opening text files in `rb` mode on python 3, which breaks `json.load`.  These issues prevent `iotile build` from working correctly on python 3.  The PR also prepares for releasing v2.8.0 of `iotile-build.
Closes #671.
=> Fix latent python 3 incompatibilities in building.

iotilecore/RELEASE.md, iotilecore/iotile/core/dev/registry.py
I found that in clear_extensions() function, we didn't clear _registered_extensions object, we are assigning a new one to it, so when we are creating 2 ComponentRegistry objects, and adding an extension to the each one, second one would have an extension that we added to the first one.
=> Fix bug with sharing extensions between ComponentRegistry objects

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py
Added exclusive variable in the **Serial** constructor(Pyserial module). This both works on windows and on linux. On windows, it just ignores this flag, while on linux, it creates a lock file.
=> 657 issue fix

iotilecore/RELEASE.md, iotilecore/setup.py, iotilecore/version.py
pypi needs another qualifier in setup.py to prevent py2 installs from getting bad packages.
=> Fix the new major release version to actually enforce py3

iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/__init__.py, iotileemulate/iotile/emulate/common/__init__.py, iotileemulate/iotile/emulate/common/emulator_errors.py, iotileemulate/iotile/emulate/demo/demo_device.py, iotileemulate/iotile/emulate/internal/emulation_loop.py, iotileemulate/iotile/emulate/internal/response.py, iotileemulate/test/test_eventloop.py, iotileemulate/version.py
This PR improves the usability of `finish_async_rpc` by handling the RPC response formatting rather than making the user convert their response to bytes.  
It also allows rpc implementations to raise a new exception `RPCRuntimeError` that will set a binary error code as the response of the RPC.  This is a common pattern inside firmware so this should reduce the work required to implement complex rpcs by letting them fail early with an error code.
- It looks like the `CrossThreadResponse` implementation of reraising an exception was broken so I also fixed it.
=> Feat emu improvement

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/arm.py, iotilebuild/iotile/build/config/site_scons/autobuild.py, iotilebuild/iotile/build/config/site_scons/unit_test_qemu.py, iotilebuild/version.py
Update `iotile-build` to support pulling out `-D` and `-I` flags from GCC and handling them via an arguments file.
This is now used by default when compiling elf files. It prevents running out of command line argument space on Windows.
It also cleans up a few places where we created an `SCons.Environment()` without overriding the default tools.  This leads to a useless warning on Windows about "VIsual Studio" not being installed.
- Tested compiling all internal elf projects and library projects to ensure that all work.
Closes #726.
Closes #714.
=> Add support for passing gcc arguments via a command file.

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/utilities.py, iotilebuild/test/test_iotilebuild/arm_def_component/SConstruct, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/linker/linker.ld, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/src/SConscript, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/src/cdb/handlers.c, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/src/cdb/progtest.cdb, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/src/cdb_application.h, iotilebuild/test/test_iotilebuild/arm_def_component/firmware/src/file_1.c, iotilebuild/test/test_iotilebuild/arm_def_component/module_settings.json, iotilebuild/test/test_iotilebuild/arm_def_component/python/arm_proxy.py, iotilebuild/test/test_iotilebuild/arm_def_component/python/lib_armtypes/file1.py, iotilebuild/test/test_iotilebuild/test_scons.py, iotilebuild/version.py
This PR adds the ability to completely remove a `defines` entry from a previous architecture in a subsequent one.  Previously it was only possible redefine it's value, not `#undefine` it entirely.  Complete removal is important when the `#define` is used by third party code that checks for its presence using `#ifdef` rather than `#if`.
Closes #730
=> Add the ability to completely undefine a -D symbol.

azure-pipelines.yml, doc_requirements.txt, iotilecore/RELEASE.md, iotilecore/iotile/core/utilities/event_loop.py, iotilecore/iotile/core/utilities/validating_wsclient.py, iotilecore/version.py, iotilegateway/RELEASE.md, iotilegateway/iotilegateway/gateway.py, iotilegateway/iotilegateway/main.py, iotilegateway/iotilegateway/supervisor/__init__.py, iotilegateway/iotilegateway/supervisor/service_tile.py, iotilegateway/iotilegateway/supervisor/status_client.py, iotilegateway/setup.py, iotilegateway/test/test_async_supervisor.py, iotilegateway/test/test_async_supervisor_commands.py, iotilegateway/tox.ini, iotilegateway/version.py
Since there aren't users of this function outside of the gateway, this change is self contained and avoids prematurely infecting the larger code base with asyncio. However, there is still another dependence on the ServiceStatusClient, so the new functionality has been implemented with a separate Async* naming convention. The long term goal is to deprecate the non-async code paths. 
This is a cleaner version of the other WIP PR that cuts out the dev work that explored how deep asyncio might go in the code.
- An AsyncServiceStatusClient
- An AsyncValidatingWSClient
- An EventLoop utility that enables modules to unify coroutines in a singular event loop that exists in an EventLoopThread for a given program runtime.
- Modification to the virtual_tile to wrap a coroutine-enabled …
=> Migrate the ServiceStatusClient to use asynchronous behavior.

iotilecore/iotile/core/utilities/__init__.py, iotilecore/iotile/core/utilities/event_loop.py, iotilecore/test/test_utilities/test_eventloop.py
This PR refactors EventLoop to add support for stopping background tasks in an orderly fashion and adds basic test coverage of the task creation and shutdown process.  For increased testability, `EventLoop` is moved from class methods onto to a normal class (`BackgroundEventLoop`) and a single global instance is created named `EventLoop` for backwards compatibility.
We should probably rename `EventLoop` to something like `SharedLoop` or `GlobalLoop` to better distinguish it from the `BackgroundEventLoop` class.
- This PR is to merge into the long-running branch `extended-asyncio-upgrade` that can accumulate asyncio-related changes until we are at a point where we want to merge into `master` and declare that we're going to start maintaining backwards compatibility and release the new …
=> Feat event loop

iotilecore/iotile/core/hw/exceptions.py, iotilecore/iotile/core/hw/transport/__init__.py, iotilecore/iotile/core/hw/transport/adapter/abstract.py, iotilecore/iotile/core/hw/transport/adapter/mixin_notifications.py, iotilecore/iotile/core/hw/transport/adapter/standard.py, iotilecore/iotile/core/hw/transport/adapter/sync_wrapper.py, iotilecore/iotile/core/hw/transport/server/__init__.py, iotilecore/iotile/core/hw/transport/server/abstract.py, iotilecore/iotile/core/hw/transport/server/standard.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/__init__.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/setup.py, iotilecore/test/test_hw/test_standard_adapter.py, iotilecore/test/test_hw/test_standard_server.py, iotileemulate/iotile/emulate/transport/emulatedadapter.py
Adds  `AbstractDeviceServer` and `StandardDeviceServer` classes.  These classes are designed to unify and eventually replace `VirtualInterface` and `GatewayAgent`.  
`AbstractDeviceServer` is designed to let `iotile-gateway` load and run device servers without needing to know anything about how they serve devices.  It is intentionally left very minimal.
`StandardDeviceServer` is designed to be the reference implementation of device server functionality that most/all device servers inherit from.  As described in the documentation, it takes a single `AbstractDeviceAdapter` instance and serves multiple clients access to the devices that are reachable through that adapter.
`StandardDeviceServer` takes care of all of the tricky house-keeping around cleaning up after clients that unexpectedly …
=> Add generic device server implementation and refactor progress notifications

iotilecore/iotile/core/hw/debug/debug_manager.py, iotilecore/iotile/core/hw/transport/adapter/__init__.py, iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py, iotilecore/iotile/core/hw/transport/server/standard.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/test/test_hw/test_standard_server.py, iotilecore/test/test_hw/test_virtualadapter.py, iotilegateway/iotilegateway/device.py, iotilegateway/iotilegateway/main.py, transport_plugins/websocket/iotile_transport_websocket/device_server.py
This PR adds a wrapper class that takes a legacy instance of `DeviceAdapter` and wraps it with a modern coroutine based api that inherits from `StandardDeviceAdapter`.  This allows `iotile-gateway` to automatically support `jlink` and `bled112` transport plugins via this legacy shim.
This is step one to migrating `AdapterStream` to natively work with `AbstractDeviceAdapter` and support legacy device adapters via this shim.  Currently we natively support the legacy DeviceAdapters and work with the modern ones using a `LegacySynchronousWrapper` class.
- Add `AsynchronousModernWrapper` class that takes a legacy DeviceAdapter and turns it into something that inherits from `StandardDeviceAdapter`.  Legacy callbacks are translated to modern events and all of the legacy adapters functions are …
=> Add support for using legacy DeviceAdapters in iotile-gateway

iotileship/RELEASE.md, iotileship/iotile/ship/recipe.py, iotileship/iotile/ship/scripts/iotile_ship.py, iotileship/version.py
Bug fix to remove the binary mode from reading the yaml files.
=> Fix open mode from 'rb' to 'r' for yaml files

iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilegateway/iotilegateway/supervisor/service_manager.py, transport_plugins/websocket/iotile_transport_websocket/generic/async_client.py, transport_plugins/websocket/iotile_transport_websocket/generic/packing.py
In the EventLoop:
- Add outcome exception printouts for when cancelled tasks have an exception other than CancelledError to help debug
- Some minor style changes
In websockets:
- Switched the datetime decoder to not use bytes, similar to what we'd done in the past for the other websockets datetime things for py3
In gateway:
- short_name was used when long_name was the variable present and (I believe) intended to be used.
=> asyncio / websockets small fixes

iotilecore/iotile/core/hw/transport/adapterstream.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/iotile/core/hw/virtual/common_types.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotileemulate/iotile/emulate/virtual/emulated_tile.py, iotilegateway/iotilegateway/supervisor/client.py, iotilegateway/iotilegateway/supervisor/service_tile.py, iotiletest/iotile/mock/mock_adapter.py
Addresses #798 and #799
- Added inspectors to support async functions to be called by RPC, both by decorator and by the status client. This duplicates the async_rpc decorators in the Emulator, which haven't been removed but could be at this point.
- The VirtualAdapter now properly allows for coroutine based calls from the SupervisorClient
=> Modify the VirtualDevice to be compliant with coroutine RPCs

iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/iotile/cloud/apps/cloud_uploader.py, iotile_ext_cloud/version.py, iotilebuild/RELEASE.md, iotilebuild/iotile/build/dev/depmanager.py, iotilebuild/version.py
- You can now get a list of all python dependencies of an iotile component.  This is needed to be able to make sure those dependencies are installed during firmware CI testing.  Previously we didn't test python parts of an iotile component so the fact that this never worked wasn't an issue, now it is and is blocking us moving firmware builds to python 3.
- You can now use the cloud_uploader app to download reports from a POD without needing to enter iotile.cloud credentials.  This improves the POD-1M `tracker_app` download process so that we can just download data locally without needing to enter an unused iotile.cloud credential.
=> Cleanup minor issues in iotile-ext-cloud and iotile-build

.gitignore, transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/iotile_transport_jlink/jlink.py, transport_plugins/jlink/version.py
Fixing `_try_connect` to only execute the `on_disconnect` callback if the device had been previously connected.
=> Fix asyncio jlink adapter

iotileship/RELEASE.md, iotileship/iotile/ship/actions/ModifyJsonStep.py, iotileship/version.py
Attempting to run this step to set the iotile id would write it out as a string, in quotations.
To alleviate this, this change will allow the type of the value to be set.
Add additional optional argument to iotile-ship ModifyJsonStep
=> Adding a type option to ModifyJsonStep

iotilebuild/RELEASE.md, iotilebuild/iotile/build/config/site_scons/arm.py, iotilebuild/iotile/build/config/site_scons/autobuild.py, iotilebuild/version.py
Added a parameter that users can pass in their `SConstruct` file to add optional linker options.
Example:
```
import autobuild
elfname = 'execnrf52832'
autobuild.autobuild_arm_program(elfname, patch=True, objcopy_flags="-R .bootloader_info")
```
=> Optional objcopy flags during linking

iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/output_formats/config.py, iotilesensorgraph/iotile/sg/output_formats/snippet.py, iotilesensorgraph/version.py
Closes #813
Did a search through the rest of coretools to check for this type of conditional, but didn't find anything outside of these two files.
Note that we can cut a release of this immediately since it's dependent on iotile-core<5
=> Spot fix byte/str concats

iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/version.py, iotilebuild/RELEASE.md, iotilebuild/version.py, iotilecore/RELEASE.md, iotileemulate/RELEASE.md, iotilegateway/RELEASE.md, iotilesensorgraph/RELEASE.md, iotilesensorgraph/version.py, iotileship/RELEASE.md, iotileship/version.py, iotiletest/RELEASE.md, transport_plugins/awsiot/RELEASE.md, transport_plugins/awsiot/version.py, transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/version.py, transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/version.py, transport_plugins/native_ble/RELEASE.md, transport_plugins/native_ble/version.py, transport_plugins/websocket/RELEASE.md
The release scripts need the release notes to match the tags exactly so no `-rc1` in the release notes.  Also to avoid situations where upgrading CoreTools without passing `--pre` could pull in prereleases anyway, I am marking all of the new packages as `rc1`, even those that are backwards compatible since their `install_requires` would pull in `iotile-core 5.0.0rc1` when they were upgraded.
=> Fix releases to not have `-` character.

iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/iotile/cloud/apps/cloud_uploader.py, iotile_ext_cloud/version.py
Hotfix to support uploading readings from very old pods that don't support configuring the maximum report size.  This is a customer issue currently being hit in Zambia on some very old POD-1 family devices with out-of-date firmware.
The cloud uploader now supports those firmwares by making report size configuration opportunistic and not failing if the RPC is not supported.
@ekkizogloy Note that the default maximum report size on those PODs is 10k readings so if the customer has more than 10k readings they will need to do multiple uploads (making sure the data is acknowledged / processed by the cloud between each upload) in order to get all of the data off the POD.
=> Fix cloud uploader to support very old controller firmware.

iotilecore/iotile/core/hw/debug/debug_manager.py, transport_plugins/jlink/iotile_transport_jlink/jlink.py, transport_plugins/jlink/iotile_transport_jlink/jlink_background.py
- Jlink inherits new StandardDeviceAdapter instead of DeviceAdapter and implements new interface.
- JLinkControlThread renamed to AsyncJlink, removed thread and queue. Now AsyncJlink implement functions to interact with jlink that are called from JlinkAdapter using **run_in_executor** function in order not to block the background thread.
- Add maintenance periodical task for polling control info.
=> Refactor jlink_background.py to use asyncio event loop

azure-pipelines.yml, iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/iotile/cloud/apps/cloud_uploader.py, iotile_ext_cloud/setup.py, iotile_ext_cloud/test/test_cloud_uploader.py, iotile_ext_cloud/version.py, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/virtual/common_types.py, iotilecore/setup.py, iotilecore/version.py, tox.ini
This PR works around a firmware issue where the controller does not properly raise `RPCNotFound` when an RPC isn't found and instead raises `RPCError`. This caused a bug in `cloud_uploader` where it checks if a specific RPC is implemented.  The check fails inappropriately because it looks for `RPCNotFound` exception, which is correct, but an incorrect exception is raised.
The fix is to properly raise `RPCNotFound` from the controller tile.
@ekkizogloy This PR also adds a `save_locally` method to `cloud_uploader` that **does not interact with iotile cloud in any way** and just saves the same reports that would be uploaded locally to your computer.
=> Fix cloud_uploader app and add save_locally method

transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/iotile_transport_jlink/jlink_background.py, transport_plugins/jlink/version.py
Bug fix. Dumping memory was unstable or didn't work for large sizes. The injectable code that does the flash forensics allows reading sizes of at most 4096. My tool was violating this rule.
Had a flaw in the implementation logic. The logic was to read a variable size from a specific memory region, and if it was larger than 4096 bytes, the tool should repeat reads until the desired length has been read. I had the setup for it, but I did not implement it correctly. I had saved the offset variable that determined the next read location/size, but didn't use it for some reason.
=> Fix unstable with large lengths

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/async_packet.py, transport_plugins/bled112/version.py
A real fix for properly raising the issue should supercede this later.
This addresses #825 but is not a true solution
=> Fix the log flood caused when a bled112 dongle gets disconnected.

iotilecore/iotile/core/utilities/async_tools/event_loop.py, transport_plugins/jlink/iotile_transport_jlink/jlink.py, transport_plugins/jlink/iotile_transport_jlink/jlink_background.py
- Allow `run_executor` to be run in coroutine finalizer function
- Changed `disconnect` logic to close "rpc" interface last
- Added task to handle when iotile is `quit` to cleanup nicely
- Changed frame reading logic from one at a time to all frames available in queue at once to minimize jlink memory read/writes
- Performance enhancement by removing delays
- Fixed coroutine quitting issues because of while loop in `maintenance_coroutine`
=> Fix jlink multiple frame read

transport_plugins/bled112/blob/flash_bled112.py, transport_plugins/bled112/blob/requirements.txt
Had some issues with the script, especially related to dongles failing to reset when requested to and missing python packages. This PR fixes all known issues / feature requests
A more granular list of the changes made, ideally with links to issues
- Add an argument to specify the expected number of bled112 devices to find and then flash, error if count doesn't match. Implements #852 
- Add a requirements.txt file to ensure the correct dependencies are installed. Fixes #853 
- Fix issue where some dongles wouldn't reset when first requested (added retry to them)
@ekkizogloy
=> Make improvements and fixes to bluetooth flasher script

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/virtual/tile_based_device.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/test/test_hw/test_virtualadapter.py, iotilecore/test/test_hw/tile_config.json, iotilecore/version.py
The goal of this feature is to enable products to use tie tile_manager functionality of a controller
without actually having a controller (virtual devices).
These changes cover one areas:
- Responding to tile_manager requests for tile details on each slot
There is a new VirtualController class in the tile_based_device.py file that is included in all TileBasedDevices. By default you do not need to complete anything and placeholders will be used. The tile_manager will function always, however.
This virtual controller has an intended use case in the next release of one of our products soon and we need a released version of coretools to install it. It introduces new endpoints but doesn't modify existing ones, which warrants a patch bump.
=> Augment TileBasedDevice to have some virtual controller functionality

.pylintrc, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/virtual/tile_based_device.py, iotilecore/version.py
Small fix in the tile_based_device that actually allows the controller override to take place.
Also pushes the pylintrc change.
=> Fix tile_based_device controller override

iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/iotile/cloud/cloud.py, iotile_ext_cloud/setup.py, iotile_ext_cloud/version.py
This PR adds support to `iotile-ext-cloud` to pass additional arguments to the `iotile-cloud` Api() object that is used to make rest calls to iotile.cloud.  This is needed to be able to configure the `timeout` and `retries` parameters that were added to control what happens in the case of transient network failures.
Previously, `iotile-cloud` didn't support automatic retries on connection errors, now it does so we need this change to be able to use that ability in CoreTools.
See https://github.com/iotile/python_iotile_cloud/pull/62
This is an urgent hotfix to resolve a stability issue with an uploader running inside a network that periodically chooses to drop connections to iotile.cloud.
=> Add support for passing kwargs down to Api() object.

iotilecore/iotile/core/hw/reports/flexible_dictionary.py
Adds a trailing Z to serialized timestamps in `FlexibleDictionaryReport` 
- Adds a `tzinfo` marker when using `dateutil.parser.parse`
=> fix: add trailing Z when isoformatting datetime

transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/version.py
Initial RC was approved [here](https://github.com/iotile/coretools/pull/856).
=> Full Release JLink streaming from RC

iotilecore/RELEASE.md, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/test/test_utilities/test_eventloop.py
So far, we've been scheduling our periodic coroutines by using while loops, such as:
```python
async def _run_analytics_report(interval=5):
while 1:
compute_metrics()
await asyncio.sleep(interval)
```
This works for many cases where exactness of an interval isn't a critical factor, and when the functional logic time is insignificant compared to the interval. In production, you'd probably want a bit more sugar to handle exceptions (or you'll exit the function) and interact with your logging utilities.
However, you may want to decouple the repeat interval from the computation, and/or not have drift (though we are always subject to jitter). 
There is a new ability to pass a coroutine in to a function that you want to run on a periodic basis. 
```python
def launch_periodic_coroutine(self, …
```
=> Add ability to start a periodic coroutine in the SharedLoop, and test

transport_plugins/socket_lib/setup.py
Fixes the format of the long description of the package so it can be uploaded to Pypi.
=> Fixing text underline for iotile-transport-socket-lib

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md
Official introduction of our PR guidelines.
No review is necessary. I will be leaving this open for a day in case anyone has feedback. However, having approval from one of @timburke and @dkarchmer would be good just to make sure that this is something we want and not just an agenda I'm pushing.
- A new PULL_REQUEST_TEMPLATE.md
- A shareable section in CONTRIBUTING.md that the template links to, for other Arch projects to reference (via the template)
- I will be creating PRs in other Arch repos with just the template
=> Improve our contribution guides

doc/source/tutorials/streaming-data.rst, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/virtual/virtualdevice_base.py, iotilecore/version.py
This closes #902 
When going through our docs/coding challenge to make sure everything still worked, I found a couple of things to update.
It's a good thing I checked, because the bonus challenge would have been very challenging to solve otherwise.
I need to cut a release so that we can use our coding challenges (we expect them to install from a released version).
@timburke -- can you sanity check that this was the right thing to await and I'm not messing up another call that needs a non-coroutine? It seemed to work locally on the demo, at least.
I'll wait to push a new version of the docs along with my other change to the tutorial for a virtual device.
=> Fix asyncio mixup in BaseVirtualDevice (need to await a coroutine)

doc/source/conf.py, doc/source/coretools-internals.rst, doc/source/tutorials/running-a-gateway.rst, doc/source/tutorials/virtual-interfaces.rst
Closes #904
Notes in #904 describe this. We changed some of the underlying interfaces and the doc builds started crashing. It wasn't noticed because nobody really uses RTD on a regular basis, and the failures/changes were minor. This should get us a fresh set, though.
=> Update the RTD reference to updated autoclass doc.

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/iotile/core/utilities/async_tools/operation_manager.py, transport_plugins/bled112/test/util/dummy_serial.py
This PR is into a long-running branch `feat-bled112-refactor`.  It is the first in a series of PRs that are designed to move bled112 completely over to asyncio.  This PR just contains preliminary enhancements and fixes to `iotile-core` and testing utilities in `iotile-transport-bled112` needed for the port to happen.
1. Fixes the behavior of `AsynchronousModernWrapper`  to not call `stop()` twice when invoked by a HardwareManager that has `close()` called on it explicitly.
2. Fixes the very old behavior of our pyserial mocking wrapper in bled112's test files to use a proper queue for simulated reads so that we can support `cancel_read()` which is a pyserial behavior that lets us cancel a read that is in progress.  This will be used to decrease the CPU usage of running a `virtual_device` …
=> Preliminary work to Port BLED112 device adapter fully to asyncio

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/server/abstract.py, iotilecore/iotile/core/hw/transport/server/standard.py, iotilecore/iotile/core/scripts/virtualdev_script.py
Currently, the virtual-device script has no way of knowing if the underlying device server that it is hosting has encountered a fatal error and is no longer running.  Since the server runs in a background event loop, exceptions don't naturally cause the main script to exit.
This commit adds a `failed` Future() on all DeviceServers that can be set to indicate that the server has encounted a fatal error condition and stopped operation.
The virtual-device script is updated to wait on this future rather than just sleeping until Ctrl-C is hit.
An example of the new usage is:
```
$ virtual-device bled112 simple
```
If you unplug the BLED112 dongle that is serving the virtual device, it can now cleanly exit the virtual_device program.  FYI, for this new functionality to work, it requires …
=> Add support for device servers to indicate fatal errors.

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py, iotilecore/iotile/core/utilities/async_tools/event_loop.py, iotilecore/iotile/core/utilities/async_tools/operation_manager.py
@mattrunchey These commits were already reviewed and approved in the `feat-bled112-refactor` branch last week (or the week before).  I'm pulling them out and cherry-picking over to master because they're generally useful apart from that refactor and safe.
I'm working to make `feat-bled112-refactor` less massive so that we can get smaller PRs into master with backwards compatible improvements without a giant long running feature-branch merge at the end.
The current plan is:
- Move things that are backwards compatible and safe from `feat-bled112-refactor` into master (this PR) so that the feature branch becomes smaller.
- Restructure `feat-bled112-refactor` to use the code now in `iotile-transport-blelib`.
- Update feat-bled112-refactor to not swap out the current device adapter for a new …
=> Cherry-Pick safe and tested commits from `bled112-refactor` into master

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py
Recently a check was added to send_rpc_async
```Python
if self.check_is_rpc_in_progress(found_handle, services):
callback(conn_id, self.id, False, 'RPC still in progress', None, None)
return
```
This check periodically causes RPCs to fail with exception:
```
E           iotile.core.hw.exceptions.DeviceAdapterError: DeviceAdapterError: Operation send_rpc on conn 0 failed because Error writing to handle
E           Additional Information:
E           reason: Error writing to handle
E           operation: send_rpc
E           conn_id: 0
```
The impelemtation needs to be revised.
=> Comment out "RPC in progress" check

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/reports/signed_list_format.py, iotilecore/test/test_hw/test_virtualadapter.py, iotilecore/test/test_reports/test_signed_list_report.py, iotiletest/iotile/mock/devices/report_test_device.py
Recently two new auth methods were introduced: NullKey and PasswordBased. This change has broken the signed list encryption/decryption logic. 
The purpose of the PR is to simplify logic by introducing explicit report type and conversation function and replace hardcoded key type values with defined variables in AuthProvider.
=> Update decription logic for signed reports

iotile_ext_cloud/RELEASE.md, iotile_ext_cloud/iotile/cloud/apps/ota_updater.py, iotile_ext_cloud/iotile/cloud/cloud.py, iotile_ext_cloud/iotile/cloud/config.py
This PR adds new config option `cloud:verify-server`, value is bool, `True` by default.
This allows to disable verification of cloud server TLS certificate. It is useful when user call cloud API being behind firewall that replaces TLS certificate with self-signed one.
- added config option `cloud:verify-server`
- instantiate Api object with `verify` param
- pass `verify` param when calling cloud server with `requests`
- disable throwing `InsecureRequestWarning` when `cloud:verify-server` is `False`
Closes #952 
Closes #953
=> Add config "cloud:verify-server"

iotile_ext_cloud/version.py
This PR contains one simple fix.
I have missed to updated a version number in a version.py module in PR #960  . 
This prevents from releasing new version of `iotile-ext-cloud`.
=> Update version number in a version.py module

azure-pipelines.yml, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/transport/adapterstream.py
Executing "disconnect" command fails if device connection was interrupted. 
It could be reproduced in a way described in #958 
1) Connect to an AP
2) Turn off AP (remove power)
3) Disconnect from AP (fails)
4) Connect to AP or any other device (fails due to "already connected")
This PR fixes this issue.
The fix is simple:
```
-   self._loop.run_coroutine(self.adapter.disconnect(0))
+   if not self.connection_interrupted:
+       self._loop.run_coroutine(self.adapter.disconnect(0))
```
If `self.connection_interrupted` if set to `True` then it means that all necessary routines triggered by the call `self.adapter.disconnect(0)` are already executed when "disconnect" event (device connection got interrupted) was handled.
Closes #958
=> Fix for "disconnect" command execution when connection to device is interrupted

iotilecore/RELEASE.md
The `5.0.16` version also includes the `HEAD` changes.
This was overlooked when updating the previously merged branch from master.
=> Fix release notes to include HEAD changes to 5.0.16

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/version.py
Bumping version numbers for new release of the iotile-transport-bled112 package, which includes #978.
=> Bumping versions for release of iotile-transport-bled112

doc_requirements.txt, iotilecore/RELEASE.md, iotilecore/iotile/core/hw/reports/utc_assigner.py, iotilecore/setup.py, iotilecore/version.py
This is a small PR to allow us to remove the `sortedcontainers` dependency from `iotile-core`.  The motivation is because `sortedcontainers` breaks the `nuitka` python C compiler and prevents us from statically compiling applications that include `iotile-core` even if they never use the one part of `iotile-core` that uses `sortedcontainers`.  
We only use `sortedcontainers` in one place inside CoreTools.  So, I replaced it with a purpose built small implementation that works for our usecase (without the generality of the `sortedcontainers` implementation.  As a side benefit, it's also faster (again for our use case).  Unit tests went from 7 -> 5.5 seconds after reimplementing.
1. I checked our entire codebase and there is only one other place where we use sortedcontainers in an internal …
=> Remove sortedcontainers dependency

iotilesensorgraph/RELEASE.md, iotilesensorgraph/iotile/sg/graph.py, iotilesensorgraph/iotile/sg/scripts/iotile_sgcompile.py, iotilesensorgraph/version.py
We want to be able to use checksum functionality on legacy sensorgraphs that do not have the meta tag headers such as `meta hash_address`, `meta hash_algorithm` etc. We want to be able to just calculate the checksum of the `.sgf` as it is.
- Fixed a bug when dumping the config variables to build a binary representation. It would dump the config variables unsorted. This fixes sorts it, since the device proxy does its hash calculation on a sorted list of config variables
- Added the `--force-checksum` option in `iotile-sgcompile` to just print the checksum in its DEBUG log. This will not actually save the checksum in any config variable in the `.sgf` file
=> Add ability to force checksum calculation despite sgf

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/reports/utc_assigner.py, iotilecore/version.py
Add the tqdm statusbar to the utc_assigner. It is imported using a `try {} except {}` block and not included as a dependency in the setup.py. 
This is needed because there are some conditions where the utc assignment takes a significant amount of time. This status bar is needed to know that software is operating correctly and not stalled.
=> Add tqdm to the utc assigner

iotilecore/RELEASE.md, iotilecore/iotile/core/hw/hwmanager.py, iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py, iotilecore/iotile/core/hw/transport/virtualadapter.py, iotilecore/version.py, iotileemulate/RELEASE.md, iotileemulate/iotile/emulate/transport/emulatedadapter.py, iotileemulate/version.py, transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/async_packet.py, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py, transport_plugins/bled112/version.py, transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/iotile_transport_jlink/jlink.py, transport_plugins/jlink/version.py
This PR fixes some critical bugs inside the BLED112 device adapter and makes it easier to build applications that need to know when there is a bled112 dongle removed during the application running.
The major changes are:
1. Refactors how serial port exceptions are handled inside the background command loop to ensure that `HardwareManager` commands on a bled112 dongle never hang.  Previously if there was a serial communication error, it would not trigger a failure callback.
2. Adds a new HardwareManager api, `heartbeat`.  This is implemented currently in the `bled112`, `virtual` and `emulated` device adapters and checks if the underlying bled112 dongle is functioning.  It returns True if things are good and False is there's a problem.  The purpose is to allow for polling to see if a dongle …
=> Fix bled112 hangs when dongle removed and allow for checking dongle functionality from HardwareManager

transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/server_bled112.py, transport_plugins/bled112/version.py
This fix allows VirtualDevices that use the Bled112 to transmit Broadcast V2 packets. Two of the indicator flags that marked an advertisement as V2 were incorrect.
This has been tested and the resulting packets were received by the ArchFX Setup App.
=> Correct indicator flags for Bled112 Broadcast v2 advertisements

iotilecore/setup.py, iotilecore/tox.ini
Fixes #992 
This adds a missing dependency of iotile-core, crcmod.
While testing, I found that the tox config for iotile-core was missing the NRF52 support dependency, which caused the tests to fail when running tox in iotile-core instead of as part of the entire coretools package.
=> Add missing crcmod and nrf52 dependencies

iotilecore/RELEASE.md, iotilecore/iotile/core/dev/annotated_registry.py, iotilecore/iotile/core/hw/auth/auth_chain.py, iotilecore/iotile/core/hw/auth/auth_provider.py, iotilecore/iotile/core/hw/auth/default_providers.py, iotilecore/iotile/core/hw/auth/inmemory_auth_provider.py, iotilecore/setup.py, iotilecore/version.py, transport_plugins/bled112/RELEASE.md, transport_plugins/bled112/iotile_transport_bled112/bled112.py, transport_plugins/bled112/iotile_transport_bled112/bled112_auth.py, transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py, transport_plugins/bled112/version.py
We need a way to support applications interfacing `coretools` to be able to authenticate their devices without being hung on a CLI prompt.
Currently, if a user wants to connect to a device, they must either set an environment variable `USER_KEY_<device MAC> = <key>` OR if it doesn't exist, be prompted by CLI to enter a password manually. This implementation is an issue for any application that needs to interface the password protection feature without getting blocked.
The solution was to create a new authentication provider that would allow the user to call the `InMemoryAuthProvider`'s class method to set shared passwords that the authentication logic can retrieve. See my comments in the review for a walkthrough of all the changes.
- Added a mapping of devices' connection strings and UUID …
=> Feat add inmemory authenticator

iotilecore/iotile/core/utilities/async_tools/operation_manager.py
An incorrect comparison to None prevented the list of waiter callbacks from being cleaned up when the callback was ready to call back. The result was a monotonically increasing memory leak, seen in the AP which was using the Operation Manager inside the Supervisor.
=> Fix memory leak in the Operation Manager

transport_plugins/jlink/RELEASE.md, transport_plugins/jlink/iotile_transport_jlink/jlink_background.py, transport_plugins/jlink/version.py
This PR fixes the following issue: https://github.com/iotile/coretools/issues/998
The SPI flash dumping tool was unsuccessful on certain PODs that were in a particular bricked state. The PODs were less so "bricked", but in some sort of loop. This fix addresses that corner case by halting the POD before injecting the "flash forensics" firmware blob.
To test, run the command on a POD connected via JLink.
`iotile hw --port 'jlink:device=nrf52' connect_direct 1 debug dump_memory --out_path spi_dump.bin --memory_region external --pause True`
It may take a minute to download the entire flash.
=> Fix JLink SPI Dumping Tool
