iotile/coretools

iotilecore/RELEASE.md
iotilecore/iotile/core/hw/auth/auth_chain.py
iotilecore/iotile/core/hw/auth/auth_provider.py
iotilecore/iotile/core/hw/auth/basic_auth_provider.py
iotilecore/iotile/core/hw/auth/default_providers.py
iotilecore/iotile/core/hw/auth/env_auth_provider.py
iotilecore/iotile/core/hw/hwmanager.py
iotilecore/iotile/core/hw/reports/report.py
iotilecore/iotile/core/hw/reports/signed_list_format.py
iotilecore/iotile/core/hw/transport/adapter.py
iotilecore/iotile/core/hw/transport/virtualadapter.py
iotilecore/iotile/core/hw/virtual/virtualdevice.py
iotilecore/setup.py
iotilecore/test/test_auth/test_basic_auth.py
iotilecore/test/test_auth/test_chained_auth.py
iotilecore/test/test_auth/test_env_auth.py
iotilecore/test/test_cmdr/report_test_config_hash.json
iotilecore/test/test_cmdr/report_test_config_signed.json
iotilecore/test/test_cmdr/test_virtualadapter.py
iotilecore/test/test_reports/test_reading.py
iotilecore/test/test_reports/test_report_parser.py
iotilecore/test/test_reports/test_signed_list_report.py
iotilecore/tox.ini
iotilecore/version.py
iotiletest/iotile/mock/devices/report_test_device.py

Add authentication hooks to allow for signing and verifying data received from a device.  
Also add the ability to connect to a virtual device directly from iotile tools without going through a loopback virtualinterface.  
Finally add test coverage for reporting signing and virtual devices.
Closes #93
Closes #83

Add support for signing and verifying reports and increase test coverage

---

iotilecore/iotile/core/utilities/schema_verify/__init__.py
iotilecore/iotile/core/utilities/schema_verify/float_verify.py
iotilegateway/iotilegateway/main.py
iotilegateway/iotilegateway/supervisor/command_formats.py
iotilegateway/iotilegateway/supervisor/main.py
iotilegateway/iotilegateway/supervisor/service_manager.py
iotilegateway/iotilegateway/supervisor/states.py
iotilegateway/iotilegateway/supervisor/status_client.py
iotilegateway/iotilegateway/supervisor/ws_handler.py
iotilegateway/test/test_message_handling.py
iotilegateway/test/test_supervisor.py
iotiletest/RELEASE.md
iotiletest/iotile/fixture/subprocess_fixture.py
iotiletest/version.py
scripts/status.py
transport_plugins/bled112/RELEASE.md
transport_plugins/bled112/version.py

Add support for sticky headline messages from services

---

doc/source/introduction.rst
doc/source/tutorials.rst

tutorial .rst changes

---

doc/source/tutorials/running-a-gateway.rst
doc/source/tutorials/virtual-interfaces.rst

Updated Tutorials 3 and 4 with simple text edits.
If we want to invest more time into tutorials then I can create a few more figures that may help.  I would focus on drawing diagrams so people understand

Tutorial update

---

doc/source/tutorials.rst
doc/source/tutorials/running-a-gateway.rst
doc/source/tutorials/sensor-graph-advanced.rst
doc/source/tutorials/sensor-graph-intro.rst
doc/source/tutorials/sensor-graph-usage.rst
iotiletest/RELEASE.md
iotiletest/iotile/mock/devices/sg_test_device.py
iotiletest/setup.py
iotiletest/version.py

This PR primarily added two more tutorials on how to use and program sensor graphs into devices.
It also adds a test device to iotile-test that is useful for injecting random data into a sensor graph for testing.
Closes #206

Add sensor graph usage and programming tutorials

---

iotile_ext_cloud/iotile/cloud/cloud.py

the device lookup method was changed to conditionally search by project or search for all devices

adds promiscuous mode support to coretools

---

iotilesensorgraph/RELEASE.md
iotilesensorgraph/iotile/sg/parser/scopes/trigger_scope.py
iotilesensorgraph/version.py

Bugfix stream allocator when given an input stream

---

iotile_ext_cloud/RELEASE.md
iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/version.py

Add the ability to log in once during interactive sessions

---

iotilesensorgraph/iotile/sg/processors.py
iotilesensorgraph/test/sensor_graphs/count.sgf
iotilesensorgraph/test/test_compiler.py

Issue 256 fix - copy_count_a not emptying FIFO input

---

iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/iotile/cloud/utilities.py
iotile_ext_cloud/test/test_login.py

Adds a new function under ` iotile cloud check_time`, that checks if the local system time is consistant with the iotile.cloud one, as defined in its HTTP response headers

Feat check time

---

iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/test/large_mock_answer.json
iotile_ext_cloud/test/test_login.py

Adds `iotile cloud get_fleet {fleet_id}` to get information about a fleet's devices
Adds `iotile cloud get_whitelist {device_id}` to get a list of devices this device is supposed to manage
Unit tested
Also minor changes / cleanup in test_check_time function

Feat fleets

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/templates/config_variables_c.c
iotilebuild/iotile/build/tilebus/descriptor.py
iotilebuild/version.py

Closes #267
Fixes descriptor and config_variables_c.c template.
Add in feature for config variable arrays.

Feat config array

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/templates/config_variables_c.c
iotilebuild/iotile/build/tilebus/descriptor.py
iotilebuild/version.py

Revert "Feat config array"

---

iotiletest/RELEASE.md
iotiletest/iotile/fixture/device_fixture.py
iotiletest/version.py

Make test fixtures more robust against noise

---

iotilesensorgraph/RELEASE.md
iotilesensorgraph/iotile/sg/parser/language.py
iotilesensorgraph/iotile/sg/stream.py
iotilesensorgraph/test/test_datastream.py
iotilesensorgraph/version.py

- Update default behavior to include important system break information
with user streamers.
Closes #275

Add support for combined and user streams

---

iotile_ext_cloud/RELEASE.md
iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/iotile/cloud/config.py
iotile_ext_cloud/version.py

Add support for device tokens

---

iotilecore/iotile/core/hw/virtual/tile_based_device.py
iotilecore/iotile/core/hw/virtual/virtualtile.py
iotilecore/test/test_hw/virtual_tile.py

Allows virtual tiles to be instanciated with their virtual device as an argument

Virtual tile access to device

---

iotilegateway/iotilegateway/supervisor/service_tile.py

Fixed an issue when creating service_delegate tiles

Fixed supervisor tile init

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/templates/config_variables_c.c
iotilebuild/iotile/build/tilebus/descriptor.py
iotilebuild/test/test_iotilebuild/component_nodependskey/build/output/module_settings.json
iotilebuild/test/test_tilebus/configarray.mib
iotilebuild/test/test_tilebus/test_parse_mib.py
iotilebuild/version.py

Fix code generation for optional array config variables

---

iotilesensorgraph/RELEASE.md
iotilesensorgraph/iotile/sg/optimizer/passes/downgrade_copyall.py
iotilesensorgraph/iotile/sg/optimizer/passes/remove_copylatest.py
iotilesensorgraph/iotile/sg/scripts/iotile_sgrun.py
iotilesensorgraph/iotile/sg/sim/simulator.py
iotilesensorgraph/iotile/sg/sim/stimulus.py
iotilesensorgraph/iotile/sg/sim/trace.py
iotilesensorgraph/iotile/sg/slot.py
iotilesensorgraph/iotile/sg/stream.py
iotilesensorgraph/iotile/sg/streamer.py
iotilesensorgraph/iotile/sg/streamer_descriptor.py
iotilesensorgraph/test.txt
iotilesensorgraph/test/test_compiler.py
iotilesensorgraph/test/test_optimizer/conftest.py
iotilesensorgraph/test/test_optimizer/sensor_graphs/complex_gates.sgf
iotilesensorgraph/test/test_optimizer/test_complex_gate.py
iotilesensorgraph/test/test_sgrun.py
iotilesensorgraph/test/test_simulator.py
iotilesensorgraph/test/test_slotid.py
iotilesensorgraph/version.py

Adds support for tracing simulations and defining simulation stimuli during execution.  Also improves optimization and fixes one edge case where the optimizer incorrectly optimized a specific situation.
Closes #321 
Closes #320 
Closes #318
Closes #317
Closes #319

Add support for tracing simulations and defining stimuli

---

iotile_ext_cloud/RELEASE.md
iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/test/conftest.py
iotile_ext_cloud/test/test_iotile_cloud.py
iotile_ext_cloud/version.py

set_device_template. check ap/os tags

---

iotile_ext_cloud/RELEASE.md
iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/test/test_iotile_cloud.py
iotile_ext_cloud/version.py

addresses https://github.com/iotile/coretools/issues/324

Feat device acknowledgements

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/templates/command_map_c.h.tpl
iotilebuild/version.py

@x24ling This fixes the firmware versioning issue.  I'll rerelease updates with the fixed version information.
Closes https://github.com/iotile/con_btc1/issues/53

Fix version assignment bug

---

iotile_ext_cloud/RELEASE.md
iotile_ext_cloud/iotile/cloud/cloud.py
iotile_ext_cloud/version.py

set_device_template staff flag, app_tag param in set_sensorgraph

---

iotiletest/RELEASE.md
iotiletest/iotile/mock/devices/report_test_device_proxy.py
iotiletest/version.py

these are additions to allow the ReportTestDevice to be fully testable.

Feat patch report testing device

---

iotilesensorgraph/RELEASE.md
iotilesensorgraph/iotile/sg/parser/statements/subtract_statement.py
iotilesensorgraph/iotile/sg/processors.py
iotilesensorgraph/setup.py
iotilesensorgraph/version.py

replace subtract_a_from_b with subtract_afromb, like in lib_controller

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/build/depends.py
iotilebuild/test/test_iotilebuild/arm_component/module_settings.json
iotilebuild/version.py

Fix regression in ProductResolver

---

iotilecore/setup.py
tox.ini

Fix tox.ini to remove futures dependency from python3 build.

Bug py3 futures

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/site_scons/unit_test_qemu.py
iotilebuild/version.py

Unit tests now work on controller firmware.

Hardcode cortex-m0 architecture for qemu unit tests

---

transport_plugins/bled112/RELEASE.md
transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py
transport_plugins/bled112/version.py

Add support for broadcast readings in virtual bled112 adapter.

---

iotilebuild/RELEASE.md
iotilebuild/iotile/build/config/site_scons/autobuild.py
iotilebuild/iotile/build/config/site_scons/trub_script.py
iotilebuild/version.py
iotileship/RELEASE.md
iotileship/iotile/ship/actions/sync_cloud_step.py
iotileship/iotile/ship/actions/verify_device_step.py
iotileship/version.py

Addresses the following:
iotile-ship
-VerifyDeviceStep uses shared resources #489
-SyncCloudStep has overwrite (default false) parameter #490 
iotile-build
-autobuild_trub_script(file_name, slot_assignments=None, os_info=None, sensor_graph=None, app_info=None)  #488

Upgrade iotile ship

---

iotile_ext_cloud/iotile/cloud/apps/cloud_uploader.py
iotilecore/iotile/core/hw/reports/flexible_dictionary.py

Add function to get/set the report size for upload. Used for uploading the 'alpha' POD-1M data.

Add support to change report size.

---

iotileship/RELEASE.md
iotileship/iotile/ship/autobuild/ship_file.py
iotileship/iotile/ship/recipe_manager.py
iotileship/iotile/ship/resources/hardware_manager.py
iotileship/version.py

Add custom steps before build, HardwareResrouce allow connect_direct

---

transport_plugins/bled112/iotile_transport_bled112/virtual_bled112.py

Fix bug with default int conversion in virtual_bled112.py

---

iotile_ext_cloud/iotile/cloud/apps/__init__.py
iotile_ext_cloud/iotile/cloud/apps/ota_updater.py

Update datetime fields to match cloud changes

Actually put the blob content to update instead of the http response

---

iotileship/RELEASE.md
iotileship/iotile/ship/actions/verify_device_step.py
iotileship/version.py

VerifyDeviceStep only set to check tags, not set them

---

iotilecore/iotile/core/scripts/virtualdev_script.py

Follows format of iotile, but doesn't have file redirect or include/exclude filtering at this time.

Add logger capability to virtual_device

---

iotilecore/iotile/core/hw/hwmanager.py

This should resolve some of the cases where it's unclear why broadcasting isn't working, but
doesn't cover all cases where another iotile software system is directly controlling
the bled112 dongle.
From #673 , doesn't fully address but will help in many cases that people currently get stuck now.
Took the opportunity to fix up minor PEP8 complaints.

Add convenience check on watch_broadcast if active-scan isn't set.

---

transport_plugins/bled112/iotile_transport_bled112/bled112.py

Counts total scan events, v1 parses, and v2 parses.
Usage:
If you have access to your adapter through the gateway, you can call these two functions, example:
`g.device_manager.adapters[0].get_scan_stats()`
`g.device_manager.adapters[0].reset_scan_stats()`
`get_scan_stats` now returns 5 things:
```
return self._scan_event_count, self._v1_scan_count, self._v2_scan_count, self._device_scan_counts, 
(time_spent - self._last_reset_time)
```
And it will show you total scan events seen, as well as v1 specific adverts and v2. You should be able to use this information to deduct the rate of packets you're processing for a given environment.
It also tracks how many v1 and v2 advertising packets have been parsed since reset for each device.
Right now this "logging" is on by default. I can have a …

Add basic event counting to the bled112 transport plugin

---

iotilecore/iotile/core/hw/proxy/proxy.py
iotilecore/iotile/core/hw/virtual/common_types.py
iotilecore/test/test_rpc/rpc_device.py
iotilecore/test/test_rpc/rpc_proxy.py
iotilecore/test/test_rpc/test_rpc.py

Fix rpc_v2 not checking that args were present before sending the rpc
Add some rpc tests
Fixes #676

Add rpc_v2 arg packing validation

---

iotilecore/RELEASE.md
iotilecore/iotile/core/hw/hwmanager.py
iotilecore/test/test_hw/simple_virtual_tile.py
iotilecore/test/test_hw/test_virtualadapter.py
iotilecore/test/test_hw/tile_config.json

664 ticket

---

transport_plugins/jlink/RELEASE.md
transport_plugins/jlink/iotile_transport_jlink/jlink_background.py
transport_plugins/jlink/version.py

Improved error checking and handling. Error message returns more useful information now.

Improved error checking and handling

---

RELEASING.md
iotilecore/setup.py

Proposed RELEASE guidelines based on a Slack conversation we had.

Update RELEASE guidelines to introduce a standardized process,

---

iotiletest/iotile/fixture/device_fixture.py
transport_plugins/jlink/iotile_transport_jlink/jlink.py
transport_plugins/jlink/iotile_transport_jlink/jlink_background.py
transport_plugins/jlink/iotile_transport_jlink/structures.py

Add handling trace and stream flags over jlink.
Add polling debug queue for traces and reports.
Add handling watch counter.
Should be merged after https://github.com/iotile/coretools/pull/826

Jlink tracing and streaming

---

iotilecore/RELEASE.md
iotilecore/iotile/core/hw/transport/adapter/mixin_notifications.py
iotilecore/iotile/core/utilities/async_tools/event_loop.py
iotilecore/version.py

Fix logging error in async task shutdown logic
Fixes #877 
New release needed so that we can add this to our node release for better performance.

Fix broadcast report bug that caused double callbacks

---

iotilegateway/RELEASE.md
transport_plugins/websocket/RELEASE.md

Had updated versions but forgotten to update release notes for gateway and websockets packages.

Fixing release notes for iotile gateway and websocket

---

iotilecore/RELEASE.md
iotilecore/version.py

@timothyfroehlich This is just the procedural PR for releasing iotilecore-5.0.8 so we can use the new periodic coroutine function in other projects that we need now. Code's already been merged and PR'd

Official release tags for iotilecore-5.0.8

---

transport_plugins/bled112/RELEASE.md
transport_plugins/bled112/version.py

Release fix for crypto package in bled112 module

---

iotilecore/RELEASE.md
iotilecore/iotile/core/hw/auth/auth_provider.py
iotilecore/iotile/core/hw/auth/cli_auth_provider.py
iotilecore/iotile/core/hw/auth/env_auth_provider.py
iotilecore/iotile/core/hw/auth/null_auth_provider.py
iotilecore/test/test_reports/test_signed_list_report.py
transport_plugins/bled112/RELEASE.md
transport_plugins/bled112/iotile_transport_bled112/bled112.py
transport_plugins/bled112/iotile_transport_bled112/bled112_auth.py
transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py
transport_plugins/bled112/iotile_transport_bled112/tilebus.py

This PR contains a bunch of BLE security refinement implemented in the controller but requires support in coretools as well. 
I decided to create a single PR as separate commits would not be functional without the controller code. @mattrunchey please, advise if it would cause problems 
Issues resolved by this PR are below, commit's message provide more background:
- Distinguish between user-key that's set via a password and one that's set to random data.
- Modify Security Level 0 for Better Symmetry with the Other Levels
- Stabilize flags/status BLE characteristic
- Consolidate 2 auth characteristics into 1
- Refactor BLE broadcast encryption flags

Stabilize BLE Security Implementation for Release

---

iotilecore/RELEASE.md
transport_plugins/bled112/iotile_transport_bled112/bled112.py
transport_plugins/bled112/iotile_transport_bled112/bled112_auth.py
transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py

The purpose of this PR is to fix error handling and simplify the signature of function pointers in authentication related code.
* Fixed 
* Type hints were added.
* Replaced complicated approach to provide an additional object to the functions with a particular member with a function pointer.
Test cases that particularly check this functionality:
`pytest -k test_BLE_authentication.py`

Fix error handling in auth process

---

iotilecore/RELEASE.md
iotilecore/version.py

Incrementing version numbers to 5.1.4 in prep for release

Release iotile-core 5.1.4

---

.github/workflows/test.yml
build_requirements.txt

as a part of migration to the common CI platform: github actions

Add linux to tested platforms

---

.github/workflows/test.yml
iotilebuild/iotile/build/config/site_scons/cfileparser.py
iotilebuild/iotile/build/scripts/iotile_emulate.py

Also explain where to get `qemu-system-gnuarmeclipse`

Make linux tests run on ubuntu-latest
